force-app/main/default/objects/Scheduled_Integration_Job__c/Scheduled_Integration_Job__c.object-meta.xml
<CustomObject>
    <label>Scheduled Integration Job</label>
    <nameField>
        <displayFormat>SIJ-{00000}</displayFormat>
        <label>Scheduled Integration Job #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Integration Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Integration_Job__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Integration_Job__c/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <label>Source Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ShopifyScheduledOperationAdapter.cls
public with sharing class ShopifyScheduledOperationAdapter implements ScheduledOperationAdapter {
    @TestVisible private static Boolean skipExecutionForTests = false;

    public void execute(Scheduled_Integration_Job__c job) {
        if (Test.isRunningTest() && skipExecutionForTests == true) {
            return;
        }
        new ShopifySyncScheduler(job.Source_Object__c, job.Direction__c == 'Out').execute(null);
    }
}